version: '3.8'
services:

  server:
    build: ./server
    image: server-image
    container_name: serverContainer
    ports:
      - "9090:9090"
      - "8081:8081"
    environment:
      - SERVER_PORT=9090

  gateway:
    build: ./gateway
    image: gateway-image
    container_name: gatewayContainer
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090
      - PORT=8080
